[torch]
 git-tree-sha1 = "21fba0f64d7e6dce93146b84ba73226f4f0f0983"
 os = "macos"

    [[torch.download]]
    sha256 = "21fba0f64d7e6dce93146b84ba73226f4f0f0983"
    url = "https://download.pytorch.org/libtorch/cpu/libtorch-macos-1.4.0.zip"

[torch]
git-tree-sha1 = "42bc9814d06d949098f5ab218be61adaa3e29c06"
os = "linux"

    [[torch.download]]
    sha256 = "42bc9814d06d949098f5ab218be61adaa3e29c06"
    url = "https://download.pytorch.org/libtorch/cu101/libtorch-cxx11-abi-shared-with-deps-1.4.0.zip"


