steps:
  - label: "GPU integration with julia v1.6"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.6"
      - JuliaCI/julia-test#v1: ~
    agents:
      queue: "juliagpu"
      cuda: "true"
      cap: sm_75
    command: |
      TMP_PROJECT=`mktemp -d`
      
      cd $$TMP_PROJECT

      touch Project.toml
      cat <<EOT > LocalPreferences.toml
      [CUDA_Runtime_jll]
      version = "10.2"
      EOT

      export CUDA_RUNTIME_ROOT=`julia --project --eval '
        using Pkg
        Pkg.add(name="CUDA_Runtime_jll", version="0.2")
        using CUDA_Runtime_jll
        println(CUDA_Runtime_jll.artifact_dir)
      '`

      ls -1 $$CUDA_RUNTIME_ROOT/lib/libcudart*
      export LD_LIBRARY_PATH=$$CUDA_RUNTIME_ROOT/lib

      cd $$BUILDKITE_BUILD_CHECKOUT_PATH
    timeout_in_minutes: 60
