steps:
  - group: C wrapper
    steps:
      - label: Build C wrapper (CPU)
        agents:
          queue: "juliagpu"
        env:
          TORCH_VARIANT: cpu
          TORCH_VERSION: "1.10.2"
        commands: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends build-essential cmake unzip
          cd /usr/local
          wget https://download.pytorch.org/libtorch/$$TORCH_VARIANT/libtorch-cxx11-abi-shared-with-deps-$$TORCH_VERSION%2B$$TORCH_VARIANT.zip
          unzip -q libtorch-*.zip
          rm libtorch-*.zip
          cd -
          export CMAKE_PREFIX_PATH=/usr/local/libtorch
          cd deps/c_wrapper
          cmake -S . -B build -DUSE_CUDA=OFF
          cmake --build build
      - label: Build C wrapper (CUDA)
        agents:
          queue: "juliagpu"
        env:
          CUDA_VERSION: "11.3.1"
          TORCH_VERSION: "1.10.2"
        commands: |
          export TORCH_VARIANT="cu$(echo $$CUDA_VERSION | cut -d . -f 1-2 | tr -d '.')"
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends build-essential cmake unzip
          cd /usr/local
          wget https://download.pytorch.org/libtorch/$$TORCH_VARIANT/libtorch-cxx11-abi-shared-with-deps-$$TORCH_VERSION%2B$$TORCH_VARIANT.zip
          unzip -q libtorch-*.zip
          rm libtorch-*.zip
          cd -
          export CMAKE_PREFIX_PATH=/usr/local/libtorch
          cd deps/c_wrapper
          cmake -S . -B build -DUSE_CUDA=ON
          cmake --build build
  - label: "GPU integration with julia v1.6"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.6"
      - JuliaCI/julia-test#v1: ~
    agents:
      queue: "juliagpu"
      cuda: "true"
      cap: sm_75
    command: |
      TMP_PROJECT=`mktemp -d`
      
      cd $$TMP_PROJECT

      touch Project.toml
      cat <<EOT > LocalPreferences.toml
      [CUDA_Runtime_jll]
      version = "10.2"
      EOT

      export CUDA_RUNTIME_ROOT=`julia --project --eval '
        using Pkg
        Pkg.add(name="CUDA_Runtime_jll", version="0.2")
        using CUDA_Runtime_jll
        println(CUDA_Runtime_jll.artifact_dir)
      '`

      ls -1 $$CUDA_RUNTIME_ROOT/lib/libcudart*
      export LD_LIBRARY_PATH=$$CUDA_RUNTIME_ROOT/lib

      cd $$BUILDKITE_BUILD_CHECKOUT_PATH
    timeout_in_minutes: 60
