steps:
  - group: C wrapper
    steps:
      - label: Build C wrapper (CPU)
        agents:
          queue: "juliagpu"
        env:
          TORCH_VARIANT: cpu
          TORCH_VERSION: "1.10.2"
          USE_CUDA: OFF
        commands: &build_c_wrapper_commands |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends build-essential cmake unzip
          cd /usr/local
          wget https://download.pytorch.org/libtorch/$$TORCH_VARIANT/libtorch-cxx11-abi-shared-with-deps-$$TORCH_VERSION%2B$$TORCH_VARIANT.zip
          unzip -q libtorch-*.zip
          rm libtorch-*.zip
          cd -
          export CMAKE_PREFIX_PATH=/usr/local/libtorch
          cd deps/c_wrapper
          cmake -S . -B build -DUSE_CUDA=$$USE_CUDA
          cmake --build build
      - label: Build C wrapper (CUDA {{ matrix.cuda_version }}, CUDNN {{ matrix.cudnn_version }}, Torch {{ matrix.torch_version }})
        agents:
          queue: "juliagpu"
        matrix:
          setup:
            cuda_version: 
              - "11.3.1"
            cudnn_version: 
              - "8.2.4"
            torch_version: 
              - "1.10.2"
          adjustments:
            - with:
                cuda_version: "11.8.0"
                cudnn_version: "8.9.4"
                torch_version: "2.1.0"
        env:
          CUDA_VERSION: "{{ matrix.cuda_version }}"
          CUDNN_VERSION: "{{ matrix.cudnn_version }}"
          TORCH_VERSION: "{{ matrix.torch_version }}"
          USE_CUDA: ON
        plugins:
          - JuliaCI/julia#v1:
              version: "1.9"
        commands:
          - |
            export CUDA_ROOT=$$(julia --project=$$(mktemp -d) --eval '
                using Pkg;
                CUDA_VERSION = VersionNumber(ENV["CUDA_VERSION"]);
                if CUDA_VERSION >= v"11" && CUDA_VERSION < v"11.4"
                    Pkg.add(name="CUDA_full_jll", version=ENV["CUDA_VERSION"]);
                    using CUDA_full_jll;
                    println(CUDA_full_jll.artifact_dir);
                else
                    Pkg.add(name="CUDA_SDK_jll", version=ENV["CUDA_VERSION"]);
                    using CUDA_SDK_jll;
                    println(CUDA_SDK_jll.artifact_dir);
                end');
                ln -s $$CUDA_ROOT/cuda /usr/local/cuda
            export PATH=$$PATH:/usr/local/cuda/bin
            
            export CUDNN_ROOT=$$(julia --project=$$(mktemp -d) --eval '
                    using Pkg;
                    Pkg.add(name="CUDNN_jll", version=ENV["CUDNN_VERSION"]);
                    using CUDNN_jll;
                    println(CUDNN_jll.artifact_dir)')
            for F in $$CUDNN_ROOT/include/cudnn*.h; do ln -s $$F /usr/local/cuda/include/$$(basename $$F); done
            for F in $$CUDNN_ROOT/lib/libcudnn*; do ln -s $$F /usr/local/cuda/lib64/$$(basename $$F); done
          - export TORCH_VARIANT="cu$(echo $$CUDA_VERSION | cut -d . -f 1-2 | tr -d '.')"
          - *build_c_wrapper_commands
  - label: "GPU integration with julia v1.6"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.6"
      - JuliaCI/julia-test#v1: ~
    agents:
      queue: "juliagpu"
      cuda: "true"
      cap: sm_75
    command: |
      TMP_PROJECT=`mktemp -d`
      
      cd $$TMP_PROJECT

      touch Project.toml
      cat <<EOT > LocalPreferences.toml
      [CUDA_Runtime_jll]
      version = "10.2"
      EOT

      export CUDA_RUNTIME_ROOT=`julia --project --eval '
        using Pkg
        Pkg.add(name="CUDA_Runtime_jll", version="0.2")
        using CUDA_Runtime_jll
        println(CUDA_Runtime_jll.artifact_dir)
      '`

      ls -1 $$CUDA_RUNTIME_ROOT/lib/libcudart*
      export LD_LIBRARY_PATH=$$CUDA_RUNTIME_ROOT/lib

      cd $$BUILDKITE_BUILD_CHECKOUT_PATH
    timeout_in_minutes: 60
