steps:
  - label: "Test using Julia {{matrix.julia_version}} and CUDA {{matrix.cuda_version}}"
    agents:
      queue: "juliagpu"
      cuda: "*"
      cap: sm_75
    matrix:
      setup:
        julia_version:
          - "1.10"
          - "1.11"
        cuda_version:
          - "10.2"
          - "11.3"
    plugins:
      - JuliaCI/julia#v1:
          version: "{{matrix.julia_version}}"
      - JuliaCI/julia-test#v1: ~
    env:
      CUDA_VERSION: "{{matrix.cuda_version}}"
    command: |
      CUDA_VERSION_MAJOR_MINOR=$$(echo $$CUDA_VERSION | cut -d . -f 1-2)
      cat <<EOT > LocalPreferences.toml
      [CUDA_Runtime_jll]
      version = "$$CUDA_VERSION_MAJOR_MINOR"
      EOT
      julia --project --eval '
        using Pkg
        CUDA_VERSION = VersionNumber(ENV["CUDA_VERSION"])
        if Base.thisminor(CUDA_VERSION) == v"11.3"
            Pkg.add(name="CUDA_Runtime_jll", version="0.7")
        else
            Pkg.add(name="CUDA_Runtime_jll")
        end
        if Base.thisminor(CUDA_VERSION) == v"10.2"
            Pkg.add(name="CUDNN_jll", version="8.2.4")
        end
      '
    timeout_in_minutes: 60
